---
- name: Fixes
  block:
  - name: Fix locale error
    # Verion 21.04.0
    # fix locale error
    ansible.builtin.command:
      cmd: "/usr/bin/sudo /usr/sbin/locale-gen de_DE.UTF-8 && /usr/sbin/update-locale LANG=de_DE.UTF-8"
    when: version_tags.awx == '21.4.0'

- name: Copy inventory file
  ansible.builtin.template:
    src: inventory.j2
    dest: '/opt/awx/tools/docker-compose/inventory'
    owner: root
    group: root
    mode: '0644'

- name: Make docker-compose-build  # noqa no-changed-when
  environment:
    # DEVEL_IMAGE_NAME: "quay.io/awx/awx_devel:{{ version_tags.awx }}" # deactivated by: 21.4.0
    LC_ALL: "C"
  ansible.builtin.command:
    cmd: make docker-compose-build
    chdir: '{{ awx_install_path }}'

- name: Start containers (docker-compose)  # noqa no-changed-when
  environment:
    # COMPOSE_TAG: '{{ version_tags.awx }}' # deactivated by: 21.4.0
    COMPOSE_UP_OPTS: '-d'
    LC_ALL: "C"
  ansible.builtin.command:
    cmd: make docker-compose
    chdir: '{{ awx_install_path }}'

- name: Clean and build the UI
  community.docker.docker_container_exec:
    container: tools_awx_1
    command: /bin/bash -c "make clean-ui ui-devel"

- name: Set admin pw
  community.docker.docker_container_exec:
    container: tools_awx_1
    command: "/bin/bash -c 'awx-manage update_password --username=admin --password={{ admin_password }}'"
  register: result

- name: Pw changed
  ansible.builtin.debug:
    var: result.stdout

- name: Load demo data
  community.docker.docker_container_exec:
    container: tools_awx_1
    command: "/bin/bash -c 'awx-manage create_preload_data'"

- name: Stop containers (docker compose)  # noqa no-changed-when -> Startet by AWX Service
  ansible.builtin.command:
    cmd: docker-compose stop
    chdir: '{{ awx_install_path }}tools/docker-compose/_sources/'
...
