---
- name: Check if certificate exist
  ansible.builtin.stat:
    path: "/etc/ssl/{{ cloudinit_fqdn }}.crt"
  register: ssl_crt_path_result

- name: Check if certificate-key exist
  ansible.builtin.stat:
    path: "/etc/ssl/{{ cloudinit_fqdn }}.key"
  register: key_path_result

- name: Remap certificate - crt
  ansible.builtin.lineinfile:
    path: /opt/awx/tools/docker-compose/_sources/docker-compose.yml
    insertafter: '      - "../../docker-compose/_sources/receptor/work_private_key.pem:/etc/receptor/work_private_key.pem"'
    line: "      - \"{{ ssl_crt_path }}:/etc/nginx/nginx.crt\""
  when: ssl_crt_path_result.stat.exists

- name: Remap certificate - key
  ansible.builtin.lineinfile:
    path: /opt/awx/tools/docker-compose/_sources/docker-compose.yml
    insertafter: '      - "../../docker-compose/_sources/receptor/work_private_key.pem:/etc/receptor/work_private_key.pem"'
    line: "      - \"{{ ssl_key_path }}:/etc/nginx/nginx.key\""
  when: ssl_crt_path_result.stat.exists
...
