---
- name: Populate service facts
  ansible.builtin.service_facts:

# Disable systemd file watcher for awx-nginx certificate if filewatcher was enabled in a previous run.
- name: Disable service awx-nginx-cert.path
  ansible.builtin.systemd:
    name: awx-nginx-cert.path
    state: stopped
    enabled: false
    masked: false
    daemon_reload: true
  when: ( 'awx-nginx-cert.path' in services ) and ( 'awx_ssl_crt_path' is defined )

# create awx service
- name: Config awx service
  block:
    - name: Copy awx.service to systemd configs
      ansible.builtin.copy:
        src: awx.service
        dest: /etc/systemd/system/awx.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable service awx.service and ensure it is not masked
      ansible.builtin.systemd:
        name: awx
        state: started
        enabled: true
        masked: false
        daemon_reload: true

# certificates
- name: Configure ACME Cert Management
  tasks: create_certificates
  block:
    # Configure ACME Cert Management for awx ssl cert is own task

    # service to restart awx if cert has changed
    - name: Copy awx-nginx-cert.service to systemd configs
      ansible.builtin.copy:
        src: awx-nginx-cert.service
        dest: /etc/systemd/system/awx-nginx-cert.service
        owner: root
        group: root
        mode: '0644'

    # whatchdog for cert
    - name: Copy awx-nginx-cert.path
      ansible.builtin.template:
        src: awx-nginx-cert.path.j2
        dest: '/etc/systemd/system/awx-nginx-cert.path'
        owner: root
        group: root
        mode: '0644'

    # wait for finisching docker compose
    - name: Wait for Docker Compose AWX to complete  # noqa no-changed-when
      ansible.builtin.shell:
        cmd: "journalctl -u awx.service | tail -1 | grep 'Finished Docker Compose AWX.'"
      register: docker_compose_awx_success
      retries: 60
      delay: 5
      until: docker_compose_awx_success

    - name: Make sure awx-nginx-cert.path service unit is running
      ansible.builtin.systemd:
        name: awx-nginx-cert.path
        state: started
        enabled: true
        masked: false
        daemon_reload: true
  when: awx_ssl_crt_path is defined
...
