---
- name: Populate service facts
  service_facts:

# Disable systemd file watcher for awx-nginx certificate if filewatcher was enabled in a previous run. 
- block:
  - name: disable service awx-nginx-cert.path
    ansible.builtin.systemd:
      name: awx-nginx-cert.path
      state: stopped
      enabled: no
      masked: no
      daemon_reload: yes
    when: ("'awx-nginx-cert.path' in services" | bool) and (hostvars['localhost']['awx_nginx_crt_path'] is defined)

# create awx service
- block:
  - name: copy awx.service to systemd configs
    ansible.builtin.copy:
      src: awx.service
      dest: /etc/systemd/system/awx.service
      owner: root
      group: root
      mode: '0644'

  - name: Enable service awx.service and ensure it is not masked
    ansible.builtin.systemd:
      name: awx
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes

# certificates
- block:
  # service to create or renew certificates
  - name: copy awx-regenerate-certificate.service to systemd configs
    ansible.builtin.copy:
      src: awx-regenerate-certificate.service
      dest: /etc/systemd/system/awx-regenerate-certificate.service
      owner: root
      group: root
      mode: '0644'

  # Bash script to regenerate certificates new or renew
  - name: copy awx-regenerate-certificate.sh
    ansible.builtin.template:
      src: awx-regenerate-certificate.sh.j2
      dest: '/usr/local/bin/awx-regenerate-certificate.sh'
      owner: root
      group: root
      mode: '0770'

  - name: Enable service awx.service and ensure it is not masked
    ansible.builtin.systemd:
      name: awx-regenerate-certificate
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes
  
  # restart awx if cert has changed
  - name: copy awx-nginx-cert.service to systemd configs
    ansible.builtin.copy:
      src: awx-nginx-cert.service
      dest: /etc/systemd/system/awx-nginx-cert.service
      owner: root
      group: root
      mode: '0644'

  # whatchdog for cert 
  - name: copy awx-nginx-cert.path
    ansible.builtin.template:
      src: awx-nginx-cert.path.j2
      dest: '/etc/systemd/system/awx-nginx-cert.path'
      owner: root
      group: root
      mode: '0644'

  # wait for finisching docker compose
  - name: Wait for Docker Compose AWX to complete
    shell: journalctl -u awx.service | tail -1 | grep 'Finished Docker Compose AWX.'
    register: docker_compose_awx_success
    retries: 60
    delay: 5
    until: docker_compose_awx_success

  - name: Make sure awx-nginx-cert.path service unit is running
    ansible.builtin.systemd:
      name: awx-nginx-cert.path
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes
  when: hostvars['localhost']['awx_nginx_crt_path'] is defined
...
