---
# Create database as container
- name: pull postgres
  community.docker.docker_image:
    name: postgres
    source: pull
    tag: '{{ version_tags.postgres }}'
    pull:
      platform: amd64

- name: create container postgres
  community.docker.docker_container:
    name: guac-postgres
    image: 'postgres:{{ version_tags.postgres }}'
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: '{{ vault_guacamole.postgres_user_name }}'
      POSTGRES_PASSWORD: '{{ vault_guacamole.postgres_password }}'
      POSTGRES_DB: '{{ postgres.db_name }}'
    volumes:
      - '{{ postgres.data_dir }}:/var/lib/postgresql/data'
...